### ISSUE TITLE
First basic enemy

### ISSUE THREAD

**Issue by AdameBf** [PainsPerdus/gboi-kirby#2]
Make the first enemy monster with the following features:

1. [x] Sprites: a few ones for the enemy monster, one for the projectile it fires (@Ametheek your contribution is welcome there if you figure the graphical stuff out before I do ;) )
2. [ ] Ability to fire a projectile (function).
2a. Projectile direction choice should depend on the player's position. Only 4 directions will be possible for a start: Down, Up, Right, Left.
2b. Possible testing idea: fires one shot every X clock ticks. 
3. [x] Has a life bar (variable)
4. [x] Can lose HP (can be tested with damage over time that triggers every X clock ticks)
5. [ ] Detect collisions with player projectiles

If you can think of anything else, let me know!

**Comment by yberreby** [comment]
>  Sprites: one for the enemy monster, one for the projectile it fires (@Ametheek your contribution is welcome there if you figure the graphical stuff out before I do ;) )

Just one sprite? (8x8 or 8x16)

**Comment by AdameBf** [comment]
> 
> 
> > Sprites: one for the enemy monster, one for the projectile it fires (@Ametheek your contribution is welcome there if you figure the graphical stuff out before I do ;) )
> 
> Just one sprite? (8x8 or 8x16)
> The projectile should be very small with a lot of transparency, then, I guess.

Yeah, that wasn't the exact intention. Item 1 reworded.
